# Generated by Django 6.0.2 on 2026-02-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo embed URL', null=True),
        ),
    ]
